### PR TITLE
Customizable xapkreader.xml data now read upon installing the plugin

### PR DESCRIPTION
**Pull request by coladict**
With this change users are no longer forced to commit files from the plugin in order to keep their configuration. They simply have to keep their root config.xml up to date by setting some `variable` tags in the `plugin` tag that defines this plugin. The only required value that does not have a default is `XAPK_PUBLIC_KEY`, because it would be different for every developer/team.
In the examples I use my own url, since this is not (yet) in the main project.

```xml
    <plugin name="com.flyingsoftgames.xapkreader" spec="https://github.com/coladict/cordova-plugin-xapkreader#cordova-5.3.1">
		<variable name="XAPK_PUBLIC_KEY" value="INSERT YOUR VERY LONG KEY HERE" />
    </plugin>
```
Then when the project is newly cloned, all they have to run is `cordova prepare` to install the platforms and plugins.

A new user adding the plugin would previously have to use the command line

    cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader#cordova-5.3.1 --save

Now they also have to add the parameters

    --variable XAPK_PUBLIC_KEY=YOUR_VERY_LONG_KEY_HERE

Thus the full command line becomes

    cordova plugin add https://github.com/coladict/cordova-plugin-xapkreader#cordova-5.3.1 --save --variable XAPK_PUBLIC_KEY=YOUR_VERY_LONG_KEY_HERE

I tested this, and the `xapk_expansion_authority` value in `platforms/android/res/values/xapkreader.xml` is also correct, even though in the generated `plugins/android.json`, the value of `installed_plugins["com.flyingsoftgames.xapkreader"]["XAPK_EXPANSION_AUTHORITY"]` is `$PACKAGE_NAME`. The value is being replaced where it matters.

**This change requires new instructions for users.**

The `XAPK_PUBLIC_KEY` variable intentionally does not have a default value, in order to force the users to take a better look at the instructions, which will need to be written for this.

I realize this may not be the right branch to request the PR to, but this also isn't how branches should be managed. `cordova-5.3.1` should have been a tag in a `cordova-5` branch.

### CODE REVIEW

**Comment by agamemnus** [comment]
Thanks. I will modify the instructions ... at some point.

Can you tell me what the "--save" for?

**Comment by coladict** [comment]
`--save` makes Cordova write the plugin/platform definition into the `config.xml`. I read that's the recommended way to add plugins and platforms to your project and you should just have `plugins/` and `platforms/` in your `.gitignore` for cleaner repositories.

**Comment by agamemnus** [comment]
I created a new branch for this. Thanks.

**Comment by coladict** [comment]
Don't forget to update the README.md with the new instructions.

**Comment by agamemnus** [comment]
Yes. I will do that.

**Pull request merged**
