### PR TITLE
Cordova 5.0

### PR DESCRIPTION
**Pull request by agamemnus**

### CODE REVIEW

**Comment by joshbuchea** [comment]
Does this solve the issues with the plugin and Cordova 5.0?

**Comment by agamemnus** [comment]
Mostly fixed. See:

https://github.com/agamemnus/cordova-plugin-xapkreader/issues/22#issuecomment-129507165

**Comment by derksacklowski** [comment]
Hi,

i'm currently trying to build an app using cordova 5.0.0 (ionic-cli) with xapkreader plugin (cordova-5.0 branch) included. Unfortunately the build process crashes with the following error.

issue

Any ideas?

Cheers
Derk

**Comment by agamemnus** [comment]
Looks like it's not finding the directory 'cause it's appending some stuff to it... they may have been fixed in the latest 5 version... make sure to update Cordova to latest version. If that doesn't help look over the steps in the first post of the megathread.

**Comment by derksacklowski** [comment]
Hi,

thanks for your quick answer. I got a few steps further to this problem:

https://github.com/agamemnus/cordova-plugin-xapkreader/issues/22#issuecomment-109654028

"C:\mr_jigtato_free\platforms\android\build\intermediates\exploded-aar\android.......plugins. com.flyingsoftgames.xapkreader.android-sdk.extras.google.play_apk_expansion\downloader_library\unspecified\release\res\drawable-mdpi-v4\notify_panel_notification_icon_bg.png."

How did you fix this problem?

Cheers
Derk

**Comment by joshbuchea** [comment]
I was able to get this plugin working in an Ionic/Cordova 5 project and documented my steps. My notes my be a little messy and contain the bundle id of the app I was working on, but this may help someone: https://gist.github.com/joshbuchea/775711c040ab94a4efc8

**Comment by agamemnus** [comment]
I'll be updating my instructions for 5 soon, and that will be useful. Thanks.

**Comment by joshbuchea** [comment]
@agamemnus no problem. Hope it's helpful.

**Comment by agamemnus** [comment]
Hey guys, if you are subscribed to this thread, please check out the 5.3.1 branch here: https://github.com/agamemnus/cordova-plugin-xapkreader/tree/cordova-5.3.1. I am going to integrate your instructions into that version now as well, joshbuchea. Thanks.

**Pull request closed without merging**
